export default {
  bitpay: 'https://www.blockchain.com/btc-testnet', //'https://test-insight.swap.online/insight',
  // bitpay: 'https://test-insight.bitpay.com',
  etherscan: 'https://rinkeby.etherscan.io',
  bscscan: 'https://testnet.bscscan.com',
  arbitrum: 'https://rinkeby-explorer.arbitrum.io',
  maticscan: 'https://explorer-mumbai.maticvigil.com',
  ghostscan: 'https://testnet.ghostscan.io',
  nextExplorer: 'https://explore.next.exchange',
  xdai: 'https://blockscout.com/poa/sokol',
  ftmscan: 'https://testnet.ftmscan.com',
  avaxscan: 'https://testnet.snowtrace.io',
  movrscan: 'https://moonbase.moonscan.io',
  amescan: 'https://testnet.amescan.io',
  oneExplorer: 'https://explorer.pops.one',
  auroraExplorer: 'https://testnet.aurorascan.dev',
  phi_v1Explorer: '',
  phi_Explorer: '',
}
