export default {
  provider: 'https://goerli.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c',
  binance_provider: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
  matic_provider: 'https://rpc-mumbai.maticvigil.com',
  arbitrum_provider: 'https://rinkeby.arbitrum.io/rpc',
  xdai_provider: 'https://sokol.poa.network',
  ftm_provider: 'https://rpc.testnet.fantom.network/',
  avax_provider: 'https://api.avax-test.network/ext/bc/C/rpc',
  movr_provider: 'https://moonbeam-alpha.api.onfinality.io/public',
  one_provider: 'https://api.s0.b.hmny.io',
  ame_provider: 'https://testnet.amechain.io',
  aurora_provider: 'https://betanet.aurora.dev',
  phi_provider: '',
  phi_v2_provider: '',
}
