#!/bin/sh

# build
npm run build:mainnet

# update repo or clone

git clone https://caffeinum:$GITHUB_TOKEN@github.com/swaponline/mainnet.build.git
cd mainnet.build
git checkout deploy
git fetch origin
git reset --hard origin/master

# clean React code from repo
rm -rf assets
rm -rf images
rm -rf fonts
rm -rf *.css
rm -rf *.js

# update files in repo
cp -rf ../build-mainnet/* ./
# \cp build-mainnet/* mainnet.build/

# commit build to repo

DATE=`date '+%Y-%m-%d %H:%M:%S'`
git add .
git commit -m "build $DATE"
git push --force

# return back to root
cd ..

echo "Create pull request at"
echo
echo "    https://github.com/swaponline/mainnet.build/compare/master...deploy"
echo
