export default {
  home: '/',
  exchange: '/exchange',
  history: '/history',
  createWallet: '/createWallet',

  wallets: '/wallets',
  currencyWallet: '/wallet',
  swap: '/swaps',
  feed: '/feed',
  aboutUs: '/aboutUs',
  listing: 'https://listing.swap.online/',
  test: 'https://testnet.swap.online',
  main: 'https://swap.online/',
  ieo: '/IEO',
  wallet: '/wallet',
  oldWallet: 'oldWallet',
  coins: '/coins',
  partial: '/partial',
  notFound: '/NotFound',
  newPage: '/+NewPage',
  multisign: '/multisign',

  // social networks
  medium: 'https://medium.com/cointorox',
  twitter: 'https://twitter.com/atomic_wallet',
  facebook: 'https://www.facebook.com/cointorox',
  telegram: 'https://t.me/cointorox',
  bitcointalk: 'https://bitcointalk.org/index.php?topic=5064771',
  discord: '#comingsoon',
  reddit: 'https://www.reddit.com/r/cointorox',
  youtube: 'https://www.youtube.com/channel/UCmKz8Cg5_4eq1wM7AdImjww',

  // footer links
  etherdelta: 'https://etherflyer.com/trade.html?pairs=OROX-ETH',
  button: '#comingsoon',
  about: 'https://atomicswapwallet.io/about-us/',
  extension: '#comingsoon',
  career: 'https://atomicswapwallet.io/careers/',
  contacts: 'https://atomicswapwallet.io/contact-us/',
  concept: 'https://atomicswapwallet.io/about-us/',
  description: 'https://atomicswapwallet.io/about-us',
  research: 'https://atomicswapwallet.io/technical-documentation/',
  reuters: '#article',
  wiki: 'https://atomicswapwallet.io/guide/',
  github: 'https://github.com/cointorox',
  githubButton: '#comingsoon',
  bitcointalkSendTx: '#comingsoon',
  privacyPolicy: 'https://atomicswapwallet.io/privacy-policy/',
  privacyPolicyDoc: 'https://atomicswapwallet.io/privacy-policy/',
  terms: 'https://atomicswapwallet.io/terms-of-use/',
  legalOpinion: 'https://atomicswapwallet.io/legal-opinion/',
  licence: 'https://atomicswapwallet.io/license/',
  faq: [
    {
      question: 'What is the price of OROX token?',
      link: 'https://coinmarketcap.com/currencies/cointorox/',
    },
    {
      question: 'I cannot see my order, although others can see it (or it can be seen from a different browser)',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'Where are my private keys stored?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'Is KYC required?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'What swap pairs are available?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'Is there fee for trade?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'How much gas is being spent for swap?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'Min. amounts to trade?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'Got stuck while swapping coins and my coin or token has already been sent to the swap. What should I do?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'In what language is this written, and where I can find source code?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'How is AtomicSwapWallet powered by Cointorox?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'What is Atomic Swap Wallet HTML Widget?',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
    {
      question: 'Advantages of using the exchanger based on Atomicswapwallet.io DEP',
      link: 'https://atomicswapwallet.io/frequently-asked-questions/',
    },
  ],
  // footer new links
  footer: {
    exchange: 'https://Atomicswapwallet.io/wallet/exchange',
    wallet: 'https://Atomicswapwallet.io/wallet',
    widget: 'https://Atomicswapwallet.io/widget',
    chromeextension: 'https://Atomicswapwallet.io/chrome-extension',
    forstablecoin: 'https://Atomicswapwallet.io/decentralized-initial-exchange-offering/',
    fordexses: 'https://Atomicswapwallet.io/whitelabel-solution/',
    forblockchains: 'https://Atomicswapwallet.io/listing/',
    forerc20tokens: 'https://Atomicswapwallet.io/listing/',
    fornewswebsites: 'https://Atomicswapwallet.io/press-opportunities/',
    whitepaper: 'https://Atomicswapwallet.io/technical-documentation/',
    wiki: 'https://Atomicswapwallet.io/guide/',
    github: 'https://github.com/cointorox/AtomicSwapWallet',
    about: 'https://Atomicswapwallet.io/about-us/',
    agreements: 'https://Atomicswapwallet.io/terms-of-use/',
    privacypolicy: 'https://Atomicswapwallet.io/privacy-policy/',
    legal: 'https://Atomicswapwallet.io/legal-opinion/',
    contacts: 'https://Atomicswapwallet.io/contact-us/',
  },
}
