export default Object.freeze({
  DUST_SAT: 546,
  TX_SIZE: 15,

  P2PKH_IN_SIZE: 148, // P2PKH: "Pay To Public Key Hash"
  P2PKH_OUT_SIZE: 34,

  // ? 67.75 P2WPKH_IN_SIZE
  P2WPKH_IN_SIZE: 108, // P2WPKH: "Pay To Witness Public Key Hash"
  P2WPKH_OUT_SIZE: 31,

  P2WSH_OUT_SIZE: 43, // P2WSH: "Pay to Witness Script Hash"
  P2SH_OUT_SIZE: 32,

  // ? 91 P2SH_P2WPKH_IN_SIZE
  P2SH_P2WPKH_IN_SIZE: 108,

  MULTISIG_P2SH_IN_SIZE: 49,
  MULTISIG_P2WSH_IN_SIZE: 6,
  MULTISIG_P2SH_P2WSH_IN_SIZE: 6,  
})