export const initialState = {
  items: [
    {
      name: 'EOS',
      title: 'EOS',
      icon: 'eos',
      value: 'eos',
      fullTitle: 'EOS',
    },
    {
      name: 'ETH',
      title: 'ETH',
      icon: 'eth',
      value: 'eth',
      fullTitle: 'ethereum',
    },
    {
      name: 'BTC',
      title: 'BTC',
      icon: 'btc',
      value: 'btc',
      fullTitle: 'bitcoin',
    },
    // {
    //   name: 'USDT',
    //   title: 'USDT',
    //   icon: 'usdt',
    //   value: 'usdt',
    // },
    {
      name: 'NOXON',
      title: 'NOXON',
      icon: 'noxon',
      value: 'noxon',
      fullTitle: 'noxon',
    },
    {
      name: 'DRT',
      title: 'DRT',
      icon: 'drt',
      value: 'drt',
      fullTitle: 'drt',
    },
    {
      name: 'SYC',
      title: 'SYC',
      icon: 'syc',
      value: 'syc',
      fullTitle: 'Synexcoin',
    },
    {
      name: 'YUP',
      title: 'YUP',
      icon: 'yup',
      value: 'yup',
      fullTitle: 'yup',
    },
    {
      name: 'SWAP',
      title: 'SWAP',
      icon: 'swap',
      value: 'swap',
      fullTitle: 'swap',
    },
    {
      name: 'JOT',
      title: 'JOT',
      icon: 'jot',
      value: 'jot',
      fullTitle: 'jot',
    },
  ],
}
