export default {
  horizon: 'https://horizon-testnet.stellar.org',
  blocktrail: 'https://api.blocktrail.com/v1/tBTC',
  bitpay: 'https://test-insight.swap.online/insight-api',
  // bitpay: 'https://test-insight.bitpay.com/api',
  etherscan: 'https://rinkeby.etherscan.io/api',
  // usdtOmni: 'https://api.omniexplorer.info/',
  bch: 'https://trest.bitcoin.com/v2',
  ltc: 'https://testnet.litecore.io/api',
  eos: {
    chainId: 'e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473',
    httpEndpoint: 'https://jungle2.cryptolions.io',
    registerEndpoint: 'https://seven.swap.online/eos-testnet/buyaccount',
    buyAccountPriceInBTC: 0.01,
    buyAccountPaymentRecipient: 'mnCLLbtNuXfmHHbDunyjqj61o63XjxNCpG',
  },
  telos: {
    chainId: 'e17615decaecd202a365f4c029f206eee98511979de8a5756317e2469f2289e3',
    httpEndpoint: 'https://testnet.eos.miami',
    registerEndpoint: 'https://seven.swap.online/telos-testnet/newaccount',
  },
  swapsExplorer: 'https://seven.swap.online/swaps-testnet/state',
  faucet: 'https://faucet.swaponline.site/testnet/',
  btc2FAProtected: 'https://2fa.swaponline.site',
}
