import web3 from './web3'
import link from './link'

export default {
  ETH: {
    currency: 'ETH',
    chainId: '0x1',
    networkVersion: 1,
    chainName: 'Ethereum',
    rpcUrls: [web3.provider],
    blockExplorerUrls: [link.etherscan],
  },
  BNB: {
    currency: 'BNB',
    chainId: '0x38',
    networkVersion: 56,
    chainName: 'Binance Smart Chain',
    rpcUrls: [web3.binance_provider],
    blockExplorerUrls: [link.bscscan],
  },
  MATIC: {
    currency: 'MATIC',
    chainId: '0x89',
    networkVersion: 137,
    chainName: 'Polygon',
    rpcUrls: [web3.matic_provider],
    blockExplorerUrls: [link.maticscan],
  },
  ARBETH: {
    currency: 'ARBETH',
    chainId: '0xA4B1',
    networkVersion: 42161,
    chainName: 'Arbitrum',
    rpcUrls: [web3.arbitrum_provider],
    blockExplorerUrls: [link.arbitrum],
  },
  AURETH: {
    currency: 'AURETH',
    chainId: '0x4e454152',
    networkVersion: 1313161554,
    chainName: 'Aurora',
    rpcUrls: [web3.aurora_provider],
    blockExplorerUrls: [link.auroraExplorer],
  },
  XDAI: {
    currency: 'XDAI',
    chainId: '0x64',
    networkVersion: 100,
    chainName: 'Gnosis (xDai)',
    rpcUrls: [web3.xdai_provider],
    blockExplorerUrls: [link.xdai],
  },
  FTM: {
    currency: 'FTM',
    chainId: '0xfa',
    networkVersion: 250,
    chainName: 'Fantom',
    rpcUrls: [web3.ftm_provider],
    blockExplorerUrls: [link.ftmscan],
  },
  AVAX: {
    currency: 'AVAX',
    chainId: '0xa86a',
    networkVersion: 43114,
    chainName: 'Avalanche',
    rpcUrls: [web3.avax_provider],
    blockExplorerUrls: [link.avaxscan],
  },
  MOVR: {
    currency: 'MOVR',
    chainId: '0x505',
    networkVersion: 1285,
    chainName: 'Moonriver',
    rpcUrls: [web3.movr_provider],
    blockExplorerUrls: [link.movrscan],
  },
  ONE: {
    currency: 'ONE',
    chainId: '0x63564c40',
    networkVersion: 1666600000,
    chainName: 'Harmony One',
    rpcUrls: [web3.one_provider],
    blockExplorerUrls: [link.oneExplorer],
  },
  AME: {
    currency: 'AME',
    chainId: '0xb4',
    networkVersion: 180,
    chainName: 'AME Chain',
    rpcUrls: [web3.ame_provider],
    blockExplorerUrls: [link.amescan],
  },
  PHI: {
    currency: 'PHI',
    chainId: '0x1055',
    networkVersion: 4181,
    chainName: 'PHI Network',
    rpcUrls: [web3.phi_provider],
    blockExplorerUrls: [link.phiExplorer],
  },
}
