export default {
  bitpay: 'https://www.blockchain.com/btc', //'https://insight.bitpay.com',
  blockcypher: 'https://live.blockcypher.com/',
  etherscan: 'https://etherscan.io',
  bscscan: 'https://bscscan.com',
  maticscan: 'https://polygonscan.com',
  arbitrum: 'https://explorer.arbitrum.io',
  ghostscan: 'https://ghostscan.io',
  nextExplorer: 'https://explore.next.exchange',
  xdai: 'https://blockscout.com/xdai/mainnet',
  ftmscan: 'https://ftmscan.com',
  avaxscan: 'https://snowtrace.io',
  movrscan: 'https://moonriver.moonscan.io',
  oneExplorer: 'https://explorer.harmony.one',
  amescan: 'https://amescan.io',
  auroraExplorer: 'https://aurorascan.dev',
  phi_v1Explorer: 'https://explorer.phi.network',
  phi_Explorer: 'https://phiscan.com',
  fkw_Explorer: 'https://explorer.fokawa.com',
  phpx_Explorer: 'https://explorer.phpx.network',
}
