export default {
  provider: 'https://mainnet.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c',
  binance_provider: 'https://bsc-dataseed.binance.org/',
  matic_provider: 'https://rpc-mainnet.maticvigil.com',
  arbitrum_provider: 'https://arb1.arbitrum.io/rpc',
  xdai_provider: 'https://rpc.gnosischain.com',
  ftm_provider: 'https://rpc.ftm.tools',
  avax_provider: 'https://api.avax.network/ext/bc/C/rpc',
  movr_provider: 'https://rpc.moonriver.moonbeam.network',
  one_provider: 'https://api.harmony.one',
  ame_provider: 'https://node1.amechain.io',
  aurora_provider: 'https://mainnet.aurora.dev',
  phi_v1_provider: 'https://rpc1.phi.network',
  phi_provider: 'https://connect.phi.network',
  fkw_provider: 'https://mainnet-rpc.fokawa.com',
  phpx_provider: 'https://rpc.phpx.network',
}
