import TRANSACTION from './TRANSACTION'
import DEFAULT_CURRENCY_PARAMETERS from './DEFAULT_CURRENCY_PARAMETERS'
import MIN_AMOUNT from './MIN_AMOUNT'
import MIN_AMOUNT_OFFER from './MIN_AMOUNT_OFFER'
import COINS_WITH_DYNAMIC_FEE from './COINS_WITH_DYNAMIC_FEE'

export const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'
export const EVM_COIN_ADDRESS = '0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'

export default {
  ZERO_ADDRESS,
  EVM_COIN_ADDRESS,
  TRANSACTION,
  DEFAULT_CURRENCY_PARAMETERS,
  MIN_AMOUNT,
  MIN_AMOUNT_OFFER,
  COINS_WITH_DYNAMIC_FEE,
}
