#!/bin/sh

git pull

#####WIDGETS
### ETH
npm run build:mainnet-widget

npm run build:testnet-widget


# update repo or clone
#rm -rf WalletWpPlugin
git clone https://sorentobot:$1@github.com/swaponline/WalletWpPlugin.git
cd WalletWpPlugin/vendors/swap
git checkout master
git fetch origin
git reset --hard origin/master

# clean React code from repo
rm -rf bsc-mainnet
rm -rf bsc-testnet
rm -rf assets
rm -rf images
rm -rf fonts
rm -rf testnet
rm -rf mainnet
rm -rf *.css
rm -rf *.js
rm -rf *.txt
rm -rf *.map # remove source maps

# update files in repo
# make mainnet
cp -rf ../../../build-mainnet-widget/* ./
buildId=$(find -iname "app.*?.css" | sed "s/^\.\/app\.\(.*\)\.css$/\1/")

echo $buildId

mv mainnet-app.${buildId}.js app.js
mv mainnet-app.${buildId}.js.map app.js.map
mv app.${buildId}.css app.css
mv mainnet-vendor.${buildId}.js vendor.js
rm index.html
rm erc20tokens.js
# https://screenshots.wpmix.net/Telegram_9DNCH0DXYKUiL0Mo1BvVvR7WvDiea0ON.png
rm -rf assets

# make testnet
mkdir ./testnet/

cd ./testnet/

cp -rf ../../../../build-testnet-widget/* ./.
buildIdtestnet=$(find -iname "app.*?.css" | sed "s/^\.\/app\.\(.*\)\.css$/\1/")

echo $buildIdtestnet

mv testnet-app.${buildIdtestnet}.js app.js
mv testnet-app.${buildIdtestnet}.js.map app.js.map
mv app.${buildIdtestnet}.css app.css
mv testnet-vendor.${buildIdtestnet}.js vendor.js
rm index.html
rm erc20tokens.js
rm -rf assets
mv testnet-*.js ../
cd ../


#####
cd ../../

perl -pi -e "s/'MCWALLET_BUILD_VER', '.*?'/'MCWALLET_BUILD_VER', '${buildId}'/g" multi-currency-wallet-pro.php
perl -i -pe 's/\b(\d+)(?=\D*$)/$1+1/e' multi-currency-wallet-pro.php

# commit build to repo

DATE=`date '+%Y-%m-%d %H:%M:%S'`
git add .
git commit -m "build $DATE"
git push --force


# return back to root
cd ..


