#!/bin/sh

git pull

#####WIDGETS

npm run build:mainnet-widget

# update repo or clone
#rm -rf WalletWpPlugin
git clone https://sorentobot:$1@github.com/swaponline/WalletWpPlugin.git
cd WalletWpPlugin/vendors/swap
git checkout master
git fetch origin
git reset --hard origin/master

# clean React code from repo
rm -rf assets
rm -rf images
rm -rf fonts
rm -rf testnet
rm -rf *.css
rm -rf *.js

# update files in repo
cp -rf ../../../build-mainnet-widget/* ./
buildId=$(find -iname "app.*?.js" | sed "s/^\.\/app\.\(.*\)\.js$/\1/")

echo $buildId

mv app.${buildId}.js app.js
mv app.${buildId}.css app.css
mv vendor.${buildId}.js vendor.js
rm index.html
rm firebase-messaging-sw.js
rm erc20tokens.js

mkdir ./testnet/

cd ./testnet/
rm -rf assets
rm -rf images
rm -rf fonts
rm -rf testnet
rm -rf *.css
rm -rf *.js

cp -rf ../../../build-testnet-widget/* ./testnet/.
buildIdtestnet=$(find -iname "app.*?.js" | sed "s/^\.\/app\.\(.*\)\.js$/\1/")

echo $buildIdtestnet

mv app.${buildIdtestnet}.js app.js
mv app.${buildIdtestnet}.css app.css
mv vendor.${buildIdtestnet}.js vendor.js
rm index.html
rm firebase-messaging-sw.js
rm erc20tokens.js
rm -rf assets
cd ../

# https://screenshots.wpmix.net/Telegram_9DNCH0DXYKUiL0Mo1BvVvR7WvDiea0ON.png
rm -rf assets

cd ../../

perl -pi -e "s/'MCWALLET_BUILD_VER', '.*?'/'MCWALLET_BUILD_VER', '${buildId}'/g" multi-currency-wallet-pro.php
perl -i -pe 's/\b(\d+)(?=\D*$)/$1+1/e' multi-currency-wallet-pro.php

# commit build to repo

DATE=`date '+%Y-%m-%d %H:%M:%S'`
git add .
git commit -m "build $DATE"
git push --force


# return back to root
cd ..

sleep 3
wget -qO- https://growup.wpmix.net/wp-content/plugins/github_hook.php


