#!/bin/sh

git pull

#####WIDGETS
### ETH
npm run build:mainnet-widget

npm run build:testnet-widget

### BSC (Binance)

npm run build:bsc-mainnet-widget

npm run build:bsc-testnet-widget



# update repo or clone
#rm -rf WalletWpPlugin
git clone https://sorentobot:$1@github.com/swaponline/WalletWpPlugin.git
cd WalletWpPlugin/vendors/swap
git checkout master
git fetch origin
git reset --hard origin/master

# clean React code from repo
rm -rf assets
rm -rf images
rm -rf fonts
rm -rf testnet
rm -rf bsc-mainnet
rm -rf bsc-testnet
rm -rf *.css
rm -rf *.js

# update files in repo
# make mainnet
cp -rf ../../../build-mainnet-widget/* ./
buildId=$(find -iname "app.*?.js" | sed "s/^\.\/app\.\(.*\)\.js$/\1/")

echo $buildId

mv app.${buildId}.js app.js
mv app.${buildId}.css app.css
mv vendor.${buildId}.js vendor.js
rm index.html
rm erc20tokens.js
# https://screenshots.wpmix.net/Telegram_9DNCH0DXYKUiL0Mo1BvVvR7WvDiea0ON.png
rm -rf assets

# make testnet
mkdir ./testnet/

cd ./testnet/

cp -rf ../../../../build-testnet-widget/* ./.
buildIdtestnet=$(find -iname "app.*?.js" | sed "s/^\.\/app\.\(.*\)\.js$/\1/")

echo $buildIdtestnet

mv app.${buildIdtestnet}.js app.js
mv app.${buildIdtestnet}.css app.css
mv vendor.${buildIdtestnet}.js vendor.js
rm index.html
rm erc20tokens.js
rm -rf assets
cd ../

#binance - mainnet
mkdir ./bsc-mainnet
cd ./bsc-mainnet

cp -rf ../../../../build-bsc-mainnet-widget/* ./.
buildIdBscMainnet=$(find -iname "app.*?.js" | sed "s/^\.\/app\.\(.*\)\.js$/\1/")

echo $buildIdBscMainnet

mv app.${buildIdBscMainnet}.js app.js
mv app.${buildIdBscMainnet}.css app.css
mv vendor.${buildIdBscMainnet}.js vendor.js
rm index.html
rm erc20tokens.js
rm -rf assets
cd ../

#binance - testnet
mkdir ./bsc-testnet
cd ./bsc-testnet

cp -rf ../../../../build-bsc-testnet-widget/* ./.
buildIdBscTestnet=$(find -iname "app.*?.js" | sed "s/^\.\/app\.\(.*\)\.js$/\1/")

echo $buildIdBscTestnet

mv app.${buildIdBscTestnet}.js app.js
mv app.${buildIdBscTestnet}.css app.css
mv vendor.${buildIdBscTestnet}.js vendor.js
rm index.html
rm erc20tokens.js
rm -rf assets
cd ../

#####
cd ../../

perl -pi -e "s/'MCWALLET_BUILD_VER', '.*?'/'MCWALLET_BUILD_VER', '${buildId}'/g" multi-currency-wallet-pro.php
perl -i -pe 's/\b(\d+)(?=\D*$)/$1+1/e' multi-currency-wallet-pro.php

# commit build to repo

DATE=`date '+%Y-%m-%d %H:%M:%S'`
git add .
git commit -m "build $DATE"
git push --force


# return back to root
cd ..

sleep 3
wget -qO- https://growup.wpmix.net/wp-content/plugins/github_hook.php


