export default {
  enter: 'enter',
  reject: 'reject',
  firstStart: 'firstStart',
  activeTabId: 'activeTabId',
  testnetSkip: 'testnetSkip',
  storageRevision: '_revision',
  wasCautionShow: 'wasCautionShow',
  hiddenCoinsList: 'hiddenCoinsList',
  privateKeysSaved: 'privateKeysSaved',
  demoMoneyReceived: 'demoMoneyReceived',
  keychainActivated: 'keychainActivated',
  eosAccountActivated: `${process.env.ENTRY}:eos:activationFlag`,
  telosAccountActivated: `${process.env.ENTRY}:telos:activationFlag`,
  eosActivationPayment: `${process.env.ENTRY}:eos:activationPayment`,
}
