export default {
  SignUp: 'SignUpModal',
  Withdraw: 'WithdrawModal',
  Offer: 'OfferModal',
  PrivateKeys: 'PrivateKeysModal',
  EosRegister: 'EosRegisterModal',
  EosBuyAccount: 'EosBuyAccountModal',
  TelosChangeAccount: 'TelosChangeAccountModal',
  Approve: 'Approve',
  ImportKeys: 'ImportKeys',
  ShowMoreCoins: 'ShowMoreCoins',
  EthChecker: 'EthChecker',
  ReceiveModal: 'ReceiveModal',
  DownloadModal: 'DownloadModal',
  Confirm: 'Confirm',
  DeclineOrdersModal: 'DeclineOrdersModal',
  IncompletedSwaps: 'IncompletedSwaps',
}
