export default {
  SignUp: 'SignUpModal',
  Withdraw: 'WithdrawModal',
  Offer: 'OfferModal',
  PrivateKeys: 'PrivateKeysModal',
  EosRegister: 'EosRegisterModal',
  EosBuyAccount: 'EosBuyAccountModal',
  TelosRegister: 'TelosRegisterModal',
  Approve: 'Approve',
  ImportKeys: 'ImportKeys',
  ShowMoreCoins: 'ShowMoreCoins',
  EthChecker: 'EthChecker',
  ReceiveModal: 'ReceiveModal',
  DownloadModal: 'DownloadModal',
}
