export default {
  btcMnemonic: `${process.env.ENTRY}:btc:mnemonicKey`,
  ethMnemonic: `${process.env.ENTRY}:eth:mnemonicKey`,
  eth: `${process.env.ENTRY}:eth:privateKey`,
  btc: `${process.env.ENTRY}:btc:privateKey`,
  twentywords: `${process.env.ENTRY}:twentywords`,
  btcMultisig: `${process.env.ENTRY}:btcMultisig:privateKey`,
  btcMultisigOtherOwnerKey: `${process.env.ENTRY}:btcMultisig:otherOwnerKey`,
  btcSmsMnemonicKey: `${process.env.ENTRY}:btcSmsMnemonicKey`,
  ethKeychainPublicKey: `${process.env.ENTRY}:eth:keychainPublicKey`,
  btcKeychainPublicKey: `${process.env.ENTRY}:btc:keychainPublicKey`,
  btcMultisigKeychainPublicKey: `${process.env.ENTRY}:btcMultisig:keychainPublicKey`,
  // xlm: `${process.env.ENTRY}:xlm:privateKey`,
  bch: `${process.env.ENTRY}:bch:privateKey`,
  ltc: `${process.env.ENTRY}:ltc:privateKey`,
  qtum: `${process.env.ENTRY}:qtum:privateKey`,
}
